// Movie data structure with comprehensive information
const moviesData = [
    {
        id: 1,
        title: "Red Notice",
        genre: ["action", "comedy"],
        year: 2021,
        rating: 6.3,
        duration: "1h 58min",
        quality: "4K",
        poster: "https://i.postimg.cc/C5mrM9gh/red-notice.jpg",
        description: "An Interpol agent tracks the world's most wanted art thief.",
        studio: "Netflix",
        trailer: "https://www.youtube.com/embed/RjNcTBXTk4I",
        cast: ["Dwayne Johnson", "Ryan Reynolds", "Gal Gadot"]
    },
    {
        id: 2,
        title: "Spider-Man: Homecoming",
        genre: ["action", "adventure"],
        year: 2017,
        rating: 7.4,
        duration: "2h 13min",
        quality: "4K",
        poster: "img/239534-spider-man-homecoming-poster.jpg",
        description: "Peter Parker balances his life as an ordinary high school student with being a superhero.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/U0D3AOldjMU",
        cast: ["Tom Holland", "Michael Keaton", "Robert Downey Jr."]
    },
    {
        id: 3,
        title: "The Matrix Ressurections",
        genre: ["scifi", "action"],
        year: 2021,
        rating: 5.6,
        duration: "2h 28min",
        quality: "4K",
        poster: "https://i.postimg.cc/Kv3HBGtL/matrix.jpg",
        description: "Return to a world of two realities: one, everyday life; the other, what lies behind it.",
        studio: "Warner Bros",
        trailer: "https://www.youtube.com/embed/9ix7TUGVYIo",
        cast: ["Keanu Reeves", "Carrie-Anne Moss", "Yahya Abdul-Mateen II"]
    },
    {
        id: 4,
        title: "Eternals",
        genre: ["adventure", "action"],
        year: 2021,
        rating: 6.3,
        duration: "2h 37min",
        quality: "4K",
        poster: "https://i.postimg.cc/c4YNZM9V/eternals.jpg",
        description: "The saga of the Eternals, a race of immortal beings who lived on Earth.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/x_me3xsvDgk",
        cast: ["Gemma Chan", "Richard Madden", "Angelina Jolie"]
    },
    {
        id: 5,
        title: "Dune: Part One",
        genre: ["scifi", "adventure"],
        year: 2021,
        rating: 8.0,
        duration: "2h 35min",
        quality: "4K",
        poster: "https://i.postimg.cc/Y9jJP1LD/dune.jpg",
        description: "Feature adaptation of Frank Herbert's science fiction novel about the son of a noble family.",
        studio: "Warner Bros",
        trailer: "https://www.youtube.com/embed/8g18jFHCLXk",
        cast: ["Timothée Chalamet", "Rebecca Ferguson", "Oscar Isaac"]
    },
    {
        id: 6,
        title: "1917",
        genre: ["war", "drama"],
        year: 2021,
        rating: 8.2,
        duration: "1h 59min",
        quality: "4K",
        poster: "https://i.postimg.cc/q7NwVQQK/1917.jpg",
        description: "Two young British soldiers during the First World War are given an impossible mission.",
        studio: "Universal",
        trailer: "https://www.youtube.com/embed/YqNYrYUiMfg",
        cast: ["George MacKay", "Dean-Charles Chapman", "Mark Strong"]
    },
    {
        id: 7,
        title: "Shang-Chi and the Legend of the Ten Rings",
        genre: ["action", "fantasy"],
        year: 2021,
        rating: 7.4,
        duration: "2h 12min",
        quality: "4K",
        poster: "https://i.postimg.cc/d1vhmV70/shang-chi.jpg",
        description: "Martial-arts master Shang-Chi confronts the past he thought he left behind.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/8YjFbMbfXaE",
        cast: ["Simu Liu", "Awkwafina", "Tony Leung"]
    },
    {
        id: 8,
        title: "Casino Royale",
        genre: ["action", "adventure"],
        year: 2006,
        rating: 8.0,
        duration: "2h 24min",
        quality: "4K",
        poster: "https://i.postimg.cc/L6r638wM/casino-royale.jpg",
        description: "James Bond's first 00 mission, where he must defeat a private banker funding terrorists.",
        studio: "Sony",
        trailer: "https://www.youtube.com/embed/36mnx8dBbGE",
        cast: ["Daniel Craig", "Eva Green", "Mads Mikkelsen"]
    },
    {
        id: 9,
        title: "The Dark Knight",
        genre: ["action", "adventure"],
        year: 2008,
        rating: 9.0,
        duration: "2h 32min",
        quality: "4K",
        poster: "https://i.postimg.cc/Gt6rKXMj/dark-knight.jpg",
        description: "Batman sets out to dismantle the remaining criminal organizations.",
        studio: "DC",
        trailer: "https://www.youtube.com/embed/EXeTwQWrcwY",
        cast: ["Christian Bale", "Heath Ledger", "Aaron Eckhart"]
    },
    {
        id: 10,
        title: "Black Panther",
        genre: ["action", "adventure"],
        year: 2018,
        rating: 7.3,
        duration: "2h 14min",
        quality: "4K",
        poster: "https://i.postimg.cc/hjjBqk6r/panther.jpg",
        description: "T'Challa returns home to Wakanda to become king, but finds his sovereignty challenged.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/xjDjIWPwcPU",
        cast: ["Chadwick Boseman", "Michael B. Jordan", "Lupita Nyong'o"]
    },
    {
        id: 11,
        title: "Venom",
        genre: ["action", "adventure"],
        year: 2018,
        rating: 6.6,
        duration: "1h 52min",
        quality: "4K",
        poster: "https://i.postimg.cc/QtyrN6rr/venom.jpg",
        description: "A failed reporter is bonded to an alien entity, one of many symbiotes.",
        studio: "Sony",
        trailer: "https://www.youtube.com/embed/u9Mv98Gr5pY",
        cast: ["Tom Hardy", "Michelle Williams", "Riz Ahmed"]
    },
    {
        id: 12,
        title: "Lord Of The Rings: Return Of The King",
        genre: ["fantasy", "adventure"],
        year: 2003,
        rating: 9.0,
        duration: "3h 21min",
        quality: "4K",
        poster: "https://i.postimg.cc/3JgJ9TT4/LOTR.jpg",
        description: "Gandalf and Aragorn lead the World of Men against Sauron's army.",
        studio: "New Line Cinema",
        trailer: "https://www.youtube.com/embed/r5X-hFf6Bwo",
        cast: ["Elijah Wood", "Viggo Mortensen", "Ian McKellen"]
    },
    {
        id: 13,
        title: "Saving Private Ryan",
        genre: ["war", "action"],
        year: 1998,
        rating: 8.6,
        duration: "2h 49min",
        quality: "4K",
        poster: "https://i.postimg.cc/VkgsQW5z/saving-private-ryan.jpg",
        description: "Following the Normandy Landings, a group of U.S. soldiers go behind enemy lines.",
        studio: "Paramount",
        trailer: "https://www.youtube.com/embed/9CiW_DgxCnQ",
        cast: ["Tom Hanks", "Matt Damon", "Tom Sizemore"]
    },
    {
        id: 14,
        title: "Interstellar",
        genre: ["scifi", "adventure"],
        year: 2014,
        rating: 8.7,
        duration: "2h 49min",
        quality: "4K",
        poster: "https://i.postimg.cc/cHgd3qhJ/interstaller.jpg",
        description: "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
        studio: "Paramount",
        trailer: "https://www.youtube.com/embed/zSWdZVtXT7E",
        cast: ["Matthew McConaughey", "Anne Hathaway", "Jessica Chastain"]
    },
    {
        id: 15,
        title: "Gladiator",
        genre: ["action", "adventure"],
        year: 2000,
        rating: 8.5,
        duration: "2h 35min",
        quality: "4K",
        poster: "https://i.postimg.cc/y8LKr6rd/gladiator.jpg",
        description: "A former Roman General sets out to exact vengeance against the corrupt emperor.",
        studio: "Universal",
        trailer: "https://www.youtube.com/embed/owK1qxDselE",
        cast: ["Russell Crowe", "Joaquin Phoenix", "Connie Nielsen"]
    },
    {
        id: 16,
        title: "Avengers: Endgame",
        genre: ["action", "scifi"],
        year: 2019,
        rating: 8.5,
        duration: "3h 1min",
        quality: "4K",
        poster: "https://i.postimg.cc/6QSXtjKx/endgame.jpg",
        description: "After the devastating events of Infinity War, the universe is in ruins.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
        cast: ["Robert Downey Jr.", "Chris Evans", "Mark Ruffalo"]
    },
    {
        id: 17,
        title: "Wonder Woman 1984",
        genre: ["action", "adventure"],
        year: 2020,
        rating: 5.4,
        duration: "2h 31min",
        quality: "4K",
        poster: "https://i.postimg.cc/1X0h0yqy/ww84.jpg",
        description: "Diana must contend with a work colleague and businessman, whose desire for true love is catastrophic.",
        studio: "DC",
        trailer: "https://www.youtube.com/embed/XW2E2Fnh52w",
        cast: ["Gal Gadot", "Chris Pine", "Kristen Wiig"]
    },
    {
        id: 18,
        title: "Captain Marvel",
        genre: ["action", "scifi"],
        year: 2019,
        rating: 5.4,
        duration: "2h 4min",
        quality: "4K",
        poster: "https://i.postimg.cc/v85swtSC/captain-marvel.jpg",
        description: "Carol Danvers becomes one of the universe's most powerful heroes.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/Z1BCujX3pw8",
        cast: ["Brie Larson", "Samuel L. Jackson", "Ben Mendelsohn"]
    },
    {
        id: 19,
        title: "Birinch boshlanish",
        genre: ["fantasy"],
        year: 2025,
        rating: 8.5,
        duration: "2h 11min",
        quality: "4K",
        poster: "img/poster.jpg",
        description: "Fantastik Tortlik - A thrilling fantasy adventure.",
        studio: "Disney",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        cast: ["Unknown", "Unknown", "Unknown"]
    },
    {
        id: 20,
        title: "Yangi Qasoskorlar",
        genre: ["action"],
        year: 2025,
        rating: 8.0,
        duration: "2h 11min",
        quality: "4K",
        poster: "img/20653dad1856cd6aae435b229976d1c6.jpg",
        description: "Marvel - New heroes rise to save the world.",
        studio: "Marvel",
        trailer: "https://www.youtube.com/embed/dQw4w9WgXcQ",
        cast: ["Unknown", "Unknown", "Unknown"]
    }
];

// Banner movies for carousel
const bannerMovies = [
    {
        id: 19,
        title: "Birinch boshlanish",
        genre: "Fantastik Tortlik",
        year: 2025,
        duration: "2h 11min",
        quality: "4K",
        poster: "img/poster.jpg"
    },
    {
        id: 20,
        title: "Yangi Qasoskorlar",
        genre: "Marver",
        year: 2025,
        duration: "2h 11min",
        quality: "4K",
        poster: "img/20653dad1856cd6aae435b229976d1c6.jpg"
    },
    {
        id: 19,
        title: "Birinch boshlanish",
        genre: "Fantastik Tortlik",
        year: 2025,
        duration: "2h 11min",
        quality: "4K",
        poster: "img/poster.jpg"
    }
];
